### ISSUE TITLE
A constructor fn attribute for 3rd party types? 

### ISSUE THREAD

**Issue by rrichardson** [cksac/fake-rs#102]
I have a bunch of types which feature things like `hyper::Body` and `Bytes`, which don't have Dummy impls,  I also can't impl them since they're third party types. I also can't restructure the structs, because I am using them with Serde to conform to a protocol. 
Really I just want to initialize these to () and [], since I don't actually want them for my particular use case.  

Is there a way to define a constructor function, similar to serde's  `serialize_with` attribute?

**Comment by cksac** [comment]
you can use your local faker with #[dummy(faker = "MyFaker")], e.g.

```rust
use fake::{Dummy, Fake, Faker};
use zerocopy::{byteorder, ByteOrder};
use rand::Rng;


pub struct MyFaker;


impl<O: ByteOrder> Dummy<MyFaker> for byteorder::U16<O> {
    fn dummy_with_rng<R: Rng + ?Sized>(_: &MyFaker, rng: &mut R) -> Self {
        Self::new(Faker.fake_with_rng(rng))
    }
}

#[derive(Debug, Dummy)]
pub struct Foo {
    #[dummy(faker = "1000..2000")]
    order_id: usize,
    customer: String,
    paid: bool,

    #[dummy(faker = "MyFaker")]
    order: byteorder::U16<byteorder::BE>
}

fn main() {
    let f: Foo = Faker.fake();
    println!("{:?}", f);
}
