### ISSUE TITLE
Remove unsafe code at creditcard.rs

### ISSUE THREAD

**Issue by yzhang71** [cksac/fake-rs#109]
Hi team,

From scanning the repo, I detected below unsafe code, and it can be convert to safe version:
`unsafe { String::from_utf8_unchecked(bytes) }`
https://github.com/cksac/fake-rs/blob/5a26c9c3b7f81f5dcc5cbec999e8025e7399676d/fake/src/faker/impls/creditcard.rs#L43

Safe version:
`String::from_utf8(bytes).unwrap()`

**Comment by llogiq** [comment]
We know that the contained values are valid UTF-8, so what does the additional check gain us?

**Comment by yzhang71** [comment]
Hi llogiq,

Thanks for replying. 

from_utf8() is another function that also converts a slice of bytes to a string slice, but it performs checks on the input to ensure that it is a valid UTF-8 sequence. If the input is not a valid UTF-8 sequence, from_utf8 returns an Err variant of the Result type, which can be handled by the caller.

In general, it is recommended to use from_utf8 over from_utf8_unchecked because it can help catch errors and bugs in your code at runtime. However, if you are certain that the input slice is always going to be a valid UTF-8 sequence, you can use from_utf8_unchecked for a potential performance improvement.

**Comment by llogiq** [comment]
But we *do* know the string is always valid UTF-8, because it's just digits.

**Comment by yzhang71** [comment]
Ok, thanks for confirming. I will close it now.
