### ISSUE TITLE
gender on people

### ISSUE THREAD

**Issue by mothsART** [cksac/fake-rs#110]
`NameWithTitle(EN).fake()` generate firstname and title without gender notion.

There is nothing also in `FirstName(EN).fake();` to distinct by gender.

**Comment by wt** [comment]
I'm just curious. Why does this matter?

**Comment by mothsART** [comment]
Some possible applications :

- generate fake data for a html form with gender.
- generate a lot of fake datas for statitics around gender. Example : number of womans birth in 2023 with a name staring with letter A.

I mean, the best would be distinct also gender (n choices) and sex (binary).

**Comment by wt** [comment]
These both seem useless to me. Names aren't technically gendered, but only gendered socially. I am not sure why I would ever write the test

> Some possible applications :
> 
> * generate fake data for a html form with gender.

I don't understand when I would ever do this with a test lib.

> * generate a lot of fake datas for statitics around gender. Example : number of womans birth in 2023 with a name staring with letter A.

Given that names are only socially gendered, I am not sure why this would be useful for a test.

> I mean, the best would be distinct also gender (n choices) and sex (binary).

These also seem pointless or discriminatory. It seems like a useful test would only care about the general case. Basically an arbitrary list of genders. I don't even really see why it needs to be the words we really use for gender in the real world. They could be completely made up as long as they are consistent.

**Comment by mothsART** [comment]
First, In absolute termes, you're right.
However, think that social codes are deeply ingrained over a long period of time and page like https://en.wikipedia.org/wiki/Unisex_name (all names not in this list will commonly strong gendered) demonstrate it.
In reality, have a firstname (distinction of common usage and civil ?) which is inadequate to the common gender appears to be rare.
Factualy, what would the best ?
If you would be precise, keep a percentage of non-common first names by gender ?
It might be technically more complicated.

Second, There is a list of civil genders recognized by a country.
For example : this list was certainly different on Iran than in USA.
They can be look discriminatory, that not the subjet.
Civil informations aren't an opinion.

Finally : what about Sex ? Sex is not a conventionnal usage but biologic.
We are born, live and die as females or males (No cases of pure hermaphroditism have been attested in humans.), and this is immutable.

**Comment by llogiq** [comment]
I fail to see why this would matter for any test case. Fake is for fake data, not for consistent data. Creating fake test data is hard enough but requiring consistence would incur a boatload of complexity we're not willing to maintain.

Besides, your argument is based on 6th grade biology and doesn't hold up to scientific scrutiny.

**Comment by mothsART** [comment]
I understand the choice of not having consistent data.
It also reduces interest, but I respect that.

Whether my arguments on biology (or civil status) are reductive or not is not really a problem in my opinion.

Lot of things must used abstraction. (or diferent levels of abstraction)

If you always take the complexity of everything into consideration from the start, you don't do anything.
What's more, it seems to me to be at odds with the idea of not maintaining too much complexity.

Many projects who generate fakes datas are using gender and/or sex. That doesn't seem to me to be discreminatory.

I deduce that you don't want to introduce the notion of gender/sex simply to avoid any debate or critics.
