### ISSUE TITLE
Missing support for passwords with special characters

### ISSUE THREAD

**Issue by Dragonsight91** [cksac/fake-rs#116]
Something i've recently come across in an integration test: 
when using `fake::faker::internet::en::Password`, i get a password like `zM86iVOsKAno152IfiGgBtNZl6UP26joK5LSUVNH71PIQoY3bMhBBEvMZohZigkMaD2u4rIngEdqGJcKht9ZD56ynZSPdkkCd`

which isn't too bad, but it would be nice if there was a method, let's call it `PasswordWithSpecial` that took a range for the length and a string or array of length >1 to add additional characters to the mix.

example: 
```rs
#[derive(Dummy)]
struct FakeUser {
    ...
    // extra special characters
    #[dummy( faker = "PasswordWithSpecial(8..128, \" !@#$%^&*()_\")" )]
    password: String
    ...
}
```

**Comment by cksac** [comment]
you can use `StringFaker`
```rust
    let f = StringFaker::with(
        String::from("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789)(*&^%$#@!~").into_bytes(),
        8..10,
    );
```
