### ISSUE TITLE
Attributes for Minimum Length of Vector in derive(Dummy)

### ISSUE THREAD

**Issue by rrichardson** [cksac/fake-rs#124]
I'm using #[`derive(Dummy)`] to construct hundreds of test cases for a rather large serialized message protocol.  It works quite well, but one issue I run into is cases where Faker generates 0 length vectors. Unless the members are Option<_> that is a violation of the protocol, so it fails to deserialize.   I'm hoping to derive the Dummy impls, as there are dozens of types, so hand-creating them would be arduous. 

I saw in the docs that there is an annotation for integers: `#[dummy(faker = "1000..2000")]`  
I tried :  
`#[dummy(faker = "fake::vec![fake::faker::company::raw::Buzzword<fake::locales::EN>; 1..4]")]`

e.g.

```rust
type BarList = Vec<String>;
type BazList = Vec<String>;

#[derive(Dummy)]
struct Foo { 
    my_bars:  Option<BarList>,
    #[dummy(faker = "fake::vec![fake::faker::company::raw::Buzzword<fake::locales::EN>; 1..4]")]
    my_baz:  BazList,
    ....
}
```

I didn't think it'd work, but here's to hoping.   
Is there a simple way to ensure that all Vec<Strings> created are a length of 1?  Note that changing the types within the structs may not be feasible, since they're serialized and deserialized in a rather strict way.  (But maybe they could be... ) 

Thanks.

**Comment by rrichardson** [comment]
NM. I looked at the dummy_derive sub-crate and found the answer. Thanks.

**Comment by rrichardson** [comment]
@rsalmei  - Try this: 

```rust

struct MyType {
    #[dummy(faker = "(Faker, 1..4)")]
    my_data: Vec<String>,
}
```

**Comment by rsalmei** [comment]
I'd never guess that... thank you 👍
