### ISSUE TITLE
Derive `Dummy` remotely

### ISSUE THREAD

**Issue by formiat** [cksac/fake-rs#125]
Many structs (e.g., `Decimal`, `DateTime`, `Duration`, `Uuid`) don't implement `Dummy`. There is a need to have a feature like "**remote derive**" in `serde` (https://serde.rs/remote-derive.html) to derive `Dummy` outside of crates.

**Comment by cksac** [comment]
yes, you can. ref to https://github.com/cksac/fake-rs/issues/102
