### ISSUE TITLE
Multiple implementations candidates while importing the Fake Trait 

### ISSUE THREAD

**Issue by sadokmtir** [cksac/fake-rs#126]
I am having my own implementation of fake function coming from an own implemented Trait. While I want to import Fake trait in Unit tests for other structs that do not have their own fake function, I get compile error for the some structs that are not using neither the `derive dummy` nor the `fake` trait from Fake Crate.
> ^^^^ multiple `fake` found

If I get rid of importing the fake Trait from the fake Crate the error disappears, in other words if I change `use fake::{Fake, Faker};` to ` use fake::{Faker};`.

Sample of code:

```rust
trait Configurable: Display + Clone {
    #[cfg(test)]
    fn fake() -> Self
    where
        Self: Sized;
}

struct Config {
    pub token:  String,
}

impl Configurable for Config {
    #[cfg(test)]
    fn fake() -> Self {
        Self {
            token: "token".to_string(),
        }
    }
}
```

```rust
use fake::{Fake, Faker};
        async fn test_input() {
            let config = Config::fake(); ^^^^ multiple `fake` found
}

```
Is this a know Issue or why is this happening ? Why I am getting by default faker Fake Trait as part of my struct  **Configurable** ?

**Comment by cksac** [comment]
that is because the lib has `impl<T> Fake for T {}` and Fake has fake() method same name as Configurable
```rust
pub trait Fake: Sized {
    #[inline]
    fn fake<U>(&self) -> U
    where
        Self: private::FakeBase<U>,
    {
        self._fake()
    }

    #[inline]
    fn fake_with_rng<U, R: Rng + ?Sized>(&self, rng: &mut R) -> U
    where
        Self: private::FakeBase<U>,
    {
        self._fake_with_rng(rng)
    }
}
impl<T> Fake for T {}
```

I would suggest to use following instead
```rust
#[cfg_attr(test, derive(Dummy))]
struct Config {
    pub token:  String,
}

let config: Config  = Faker.fake();
```
