### ISSUE TITLE
Ability to create an '&str' without a temporary value

### ISSUE THREAD

**Issue by jmevel** [cksac/fake-rs#132]
Sorry if my request is dumb, I'm a Rust beginner, currently in the process of learning the language.

I have a `Contact` struct declared as follow:

```rust
pub struct Contact<'a> {
    pub name: &'a str,
    pub email: Email<'a>,
}
```

I'd like to create a new `Contact` like this (no need to show you my `Email` struct, I think it's quite straightforward) :

```rust
let recipient = Contact {
    name: Username().fake::<&str>(),
    email: Email::parse(SafeEmail().fake::<&str>()).unwrap(),
};
```

However when doing so, I get this error

>the trait bound `&str: Dummy<Username<EN>>` is not satisfied
the following other types implement trait `Dummy<T>`:
  <&str as Dummy<BsAdj<L>>>
  <&str as Dummy<BsNoun<L>>>
  <&str as Dummy<BsVerb<L>>>
  <&str as Dummy<Buzzword<L>>>
  <&str as Dummy<BuzzwordMiddle<L>>>
  <&str as Dummy<BuzzwordTail<L>>>
  <&str as Dummy<CityPrefix<L>>>
  <&str as Dummy<CitySuffix<L>>>
and 26 others
required for `Username<EN>` to implement `fake::private::FakeBase<&str>

If I change my code to 

```rust
let recipient = Contact {
    name: Username().fake::<String>().as_str(),
    email: Email::parse(SafeEmail().fake::<String>().as_str()).unwrap(),
};
```

Then I get this error
>temporary value dropped while borrowed
creates a temporary value which is freed while still in use

The only way around I found is to do 

```rust
let temp_name = Username().fake::<String>();
let temp_email = SafeEmail().fake::<String>();
let recipient = Contact {
    name: temp_name.as_str(),
    email: Email::parse(temp_email.as_str()).unwrap(),
};
```

Is there any way to generate an `&str` directly instead of creating "useless" temporary variables?

Thanks for your answers

**Comment by llogiq** [comment]
Yes, but I wouldn't suggest you use it: You can convert your `String` to a `Box<Str>` then put that in a `ManuallyDrop` so it lives forever. Then you can get a `'static` reference on it, but it also means your String will leak, which is likely not what you want.

Another way is to have a static interner (which is basically a HashSet of strings that you can freely borrow into) so you at least avoid leaking duplicate names, at some bookkeeping cost.

Finally, you can avoid all that and use a plain `String` instead of a `&str`.

**Comment by jmevel** [comment]
Ok thank you for taking the time to answer me.
I think, I'll do as you said and use `String` instead. The other way looks like it would lead to an overcomplicated code.

I find it odd that we have to "trick" the compiler by assigning the value to some variables because at the end of the day this is *almost* the same thing. I understand that my temporary values are dropped immediately but my variables are dropped at the end of the function but still... It just adds useless complexity to the code 🙄

**Comment by llogiq** [comment]
But that is the thing with ownership – every value must have an owner. A `&str ` is just a borrow, so the value must be owned someplace else.

**Comment by jmevel** [comment]
> But that is the thing with ownership – every value must have an owner. A `&str ` is just a borrow, so the value must be owned someplace else.

I think I should read the book a second time at some point.

I was maybe naive but I thought:

1. `fake::<&str>()` could create a `String` and own it
2. It would return us a reference to it
3. Since we have a reference to this `String`, it wouldn't be destroyed
4. The `String` would be destroyed at the end of our function when the last reference to it (our `&str`) is dropped

But apparently it doesn't work this way because the compiler tells me the temporary value is dropped immediately.

**Comment by llogiq** [comment]
The rules are:

Every value has an *owner*. Once the owner goes out of scope the value is dropped.

You can have multiple shared references or one unique reference at any given time as long as the value is alive (i.e. from initialization to dropping). References may never outlive the thing they are referencing.

So in your example, the `fake::<&str>()` would produce a `String`. Thus it can only either return or drop that string. If it would return a reference there wouldn't be any owner left, and the string would be dropped, creating a dangling reference. The compiler tells you as much.

**Comment by jmevel** [comment]
Thanks again for taking the time to explain me all of this, this is much clearer now.

Very much appreciated 🙏
