### ISSUE TITLE
Is there a way to force all `Option` members to be `Some(foo)`?

### ISSUE THREAD

**Issue by sztomi** [cksac/fake-rs#139]
In [dap-rs](https://github.com/sztomi/dap-rs), `fake` is used to generate various structures to verify their serialization against a provided JSON schema. This works reasonably well, but the specification is full off optional fields, so Fake also ends up generating many `None` values in various nested structures. For verifying the serialization, it would be best if we could somehow force everything to be `Some`. Is there a way to accomplish that with `fake`? By the way, thank you very much for this excellent library, it's godsend.

**Comment by cksac** [comment]
you can enable `always-true-rng` feature, then use it
```rust
let mut rng = AlwaysTrueRng::default();
let result: Option<i64> = Faker.fake_with_rng(&mut rng);
assert_eq!(result, Some(6442450945));
```
