### ISSUE TITLE
Add ISIN to Finance

### ISSUE THREAD

**Issue by Dejiah** [cksac/fake-rs#151]
Hi,

thanks for creating this crate - has already come in handy for quite a few use cases! :-)

I am still missing a fake for the ISIN (International Securities Identification Number), which is a commonly used identifier for financial securities (e.g. see on [Wikipedia](https://en.wikipedia.org/wiki/International_Securities_Identification_Number)).
Since it has a well-defined format with a check-digit, I think it would be a nice addition for this crate.
It also uses the ISO-3611 country codes that are included for the BIC anyway already.

If you agree, I'd be happy to provide a PR myself when I find the time in the coming few weeks.

**Comment by cksac** [comment]
ya, PR welcome 👍
