### ISSUE TITLE
Is it possible to do a 'partial' fake?

### ISSUE THREAD

**Issue by bbaldino** [cksac/fake-rs#159]
I'm wondering if there's a way to be able to set some subset of fields to specific values, and then be able to use fake-generated values for the rest of the fields?  Kinda like how with default you can do something like:

```rust
let my_struct = MyStruct {
    field_one: "hello",
    ..Default::default()   
};
```

**Comment by cksac** [comment]
you can use `#[dummy(expr = "xxx")]`
```rust
#[allow(dead_code)]
#[derive(Debug, Dummy)]
struct ExprStruct {
    #[dummy(faker = "1..100")]
    pub product_id: usize,
    #[dummy(expr = "\"Base\".into()")]
    pub fixed_value: String,
}
```

**Comment by bbaldino** [comment]
Sorry, I was referring to being able to pass a specific value in when creating an instance, not when defining the struct, is that possible?

**Comment by cksac** [comment]
you can try following. e.g.
```rust
let my_struct = MyStruct {
    field_one: "hello",
    ..Faker.fake()
};
```

**Comment by bbaldino** [comment]
Perfect! Exactly what I needed.  Thanks!
