### ISSUE TITLE
Error when defining custom struct with Dummy data from fake-rs

### ISSUE THREAD

**Issue by trevorstr** [cksac/fake-rs#169]
### Summary

I'm trying to declare a `struct` with a couple of fields, populated by fake-rs.

When I add the `#[derive(Dummy)` macro to my struct, I get an error.

### Expected Result

I expected this struct to compile.

```rust
use fake::{faker::name::raw::FirstName, Dummy, Fake};

#[derive(Debug, Dummy)]
struct Person {
    #[dummy(faker = "FirstName()")]
    first_name: String,
    last_name: String,
}
```

### Actual Result

This error occurs, on the `#[derive(...)]` line.

```
expected 1 argument, found 0rust-analyzerE0107
this struct takes 1 argument but 0 arguments were supplied
an argument is missingrustcClick for full compiler diagnostic
mod.rs(191, 9): tuple struct defined here
main.rs(4, 22): provide the argument: `(/* value */)`
dummy
proc_macro Dummy
```

<img width="524" alt="Screenshot 2024-02-15 at 10 18 41 AM" src="https://github.com/cksac/fake-rs/assets/147647647/be2c9c90-767e-4657-a10a-0e70b70cfc02">

**Comment by cksac** [comment]
import `faker::name::en` instead if not providing locale;
```
use fake::{faker::name::en::FirstName, Dummy, Fake};
```
