### ISSUE TITLE
Dummy to allow multiple fakers

### ISSUE THREAD

**Issue by NickLarsenNZ** [cksac/fake-rs#170]
I would like to generate some phone numbers and include both `PhoneNumber()` and `CellNumber()`.

Is there a way to do that already?

To give an example of what I'm after:

> [!WARNING]
> This code does not work at the time of writing

```rust
#[derive(Debug, Dummy)]
struct Foo {
    #[dummy(faker = "PhoneNumber(), CellNumber()")]
    phone_number: String,
}
```

**Comment by cksac** [comment]
added Either faker for String, https://github.com/cksac/fake-rs/blob/master/fake/examples/utils.rs
```rust
use fake::faker::phone_number::en::{CellNumber, PhoneNumber};
use fake::{utils::either, Dummy, Fake, Faker};

#[derive(Debug, Dummy)]
struct Foo {
    #[dummy(faker = "either(PhoneNumber(), CellNumber())")]
    phone_number: String,
}
```

**Comment by NickLarsenNZ** [comment]
Thanks @cksac
