### ISSUE TITLE
Minimum length word & Currencies

### ISSUE THREAD

**Issue by elpiel** [cksac/fake-rs#19]
Well I am actually doing some magic to create some dummy data for blockchain project I am working on. The hack that I use is to get a `word` and then `[0..3].to_uppercase` to create a Crypto Currency, but then I thought It might be nice to be able to define how long you want the word to be.

But I also think that it might be nice to have Currencies as well into the crate? Supporting both some existing ones and custom one.

PS: My issue will be solved by using a list and choosing a random element, I was just looking for a quick hack to make everything working :sweat_smile:

**Comment by cksac** [comment]
checkout new version `fake=^2.0`
```rust
    let f = fake::StringFaker::with(String::from("ABCDEFGHIJKLMNOPQRSTUVWXYZ").into_bytes(), 3);
    println!("{}", f.fake::<String>());

    use fake::faker::currency::en::CurrencyCode;
    let f = CurrencyCode();
    println!("{}", f.fake::<String>());

    // custom list pick is easy using `rand`
    use rand::seq::SliceRandom;
    use rand::Rng;
    let ref mut r = rand::thread_rng();
    let c = &["CCY", "ABC"].choose(r).unwrap();
    println!("{}", c);
```
