### ISSUE TITLE
Is it possible to disallow/skip certain enum variations?

### ISSUE THREAD

**Issue by srfsh** [cksac/fake-rs#193]
My use case requires me to skip a certain enum variation to be selected. It is the gRPC's "unspecified" values if you're familiar. They are used as the default value if not specified by the other end. It basically works like a `null` value in JSON, meaning if the value is null or really isn't provided, it is considered `null`.

I think my use case is quite applicable to others, as it is often the first choice to use the first variation of an enum for a "zero value". So my question is whether this is possible or not and if I can workaround it.

**Comment by cksac** [comment]
with version 2.10.0
```rust
#[derive(Eq, PartialEq, Debug, Dummy)]
enum MyEnum {
    One,
    #[dummy(skip)]
    Two,
}
```
