### ISSUE TITLE
2.10 release should've been major

### ISSUE THREAD

**Issue by gz** [cksac/fake-rs#194]
Hi thanks for the great crate it's very useful, just wanted to let you know that the last release broke with semantic versioning due to this commit which I guess would've technically made it a major release https://github.com/cksac/fake-rs/commit/b0dcd9556baba15d7d905c1634361b89c959a684

No big deal was an easy fix, just reporting it here in case anyone else is wondering what's going on

**Comment by cksac** [comment]
will keep 2.10
