### ISSUE TITLE
Consider reexporting the `rand` crate

### ISSUE THREAD

**Issue by m4tx** [cksac/fake-rs#202]
`rand` crate appears in [the public API of `fake`](https://docs.rs/fake/latest/fake/trait.Fake.html#method.fake_with_rng), but no re-export is present in the library.

This just caused me some issues, where I wanted to use `rand 0.8` and tried to test my project with minimal versions of dependencies (`cargo update -Z minimal-versions`). `fake` (version 2) crate was then forced to use `rand 0.7` which was considered by `rustc` a different library, and my `impl` of the `Fake` trait failed to compile. Re-export would have fixed this because I would be able to always use whichever `rand` crate is compatible with `fake`.

See more on the concept here: https://www.lurklurk.org/effective-rust/re-export.html . Funnily enough, it describes this exact problem with `rand` crate taken as an example.

The exact compilation error can be seen here: https://github.com/flareon-rs/flareon/actions/runs/11744681280/job/32720592470?pr=62

---

*Note that I was using fake 2 hence the dependency on `rand 0.7`, but this problem will re-appear with every `rand` bump in the future.*

**Comment by cksac** [comment]
it is reexport in v3, do you mean you want a v2 with reexport?

**Comment by m4tx** [comment]
Ah, right, indeed it is now! Sorry, I haven't seen 3.0 code before. I think it would be good to remove `#[doc(hidden)]` though and add something like `/// Re-export of the `rand` crate` to assure the users that this is indeed a public `fake` crate API that isn't going anywhere in future versions.

Not sure if it's needed in the v2 version though; probably not at this point.
