### ISSUE TITLE
dummy_country_name_locale('zh_CN')

### ISSUE THREAD

**Issue by leolong0325** [cksac/fake-rs#203]
I'm trying to use the dummy_country_name_locale('zh_CN') function to return the country name of the Chinese culture, and I've found that he does not work：
```sql
anon=# select anon.dummy_country_name_locale('zh_CN');
 dummy_country_name_locale 
---------------------------
 Nepal
(1 row)

anon=# select anon.dummy_country_name_locale('zh_CN');
 dummy_country_name_locale 
---------------------------
 Bermuda
(1 row)

anon=# select anon.dummy_country_name_locale('zh_CN');
 dummy_country_name_locale 
---------------------------
 Bahrain
(1 row)
```
But I can return the Chinese name using dummy_name_locale(“zh_CN”)：
```sql
anon=# select anon.dummy_name_locale('zh_CN');
 dummy_name_locale 
-------------------
 钟昌凯
(1 row)
```
I would like to know why this is so and how I can modify it to support Chinese country names.

Looking forward to your reply

Good luck!

**Comment by cksac** [comment]
similar issue: https://github.com/cksac/fake-rs/issues/73
the root cause is there has no zh_CN locale data, so it fallback to EN. PR welcome to add more locale data in https://github.com/cksac/fake-rs/blob/master/fake/src/locales/zh_cn.rs

**Comment by leolong0325** [comment]
Thank you for your answer!

I tried to modify the fake-2.10.0/src/locales/zh_cn.rs file and the data was returned as I expected.

I have another question. I am currently developing based on the postgresql_anonymizer extension, which depends on fake-2.10.0. I want to modify the fake-2.10.0 source code to meet my needs. How can I use my modified fake-2.10.0 code?

Looking forward to your reply again！

**Comment by leolong0325** [comment]
I am indirectly getting the fake-2.10.0 source code through cargo's dependencies. I would like to know if there is a way to get the fake-2.10.0 source code directly.

**Comment by cksac** [comment]
you can clone the repo to specific commit hash

**Comment by leolong0325** [comment]
I understand, thank you for your answer, I will close this issue
