### ISSUE TITLE
Is cli supported ?

### ISSUE THREAD

**Issue by akhildevelops** [cksac/fake-rs#206]
Hi I've been using [python's faker](https://github.com/joke2k/faker) library to generate data using CLI but it's very slow.  Thinking to use fake-rs but didn't find any doc on cli. Does it have CLI ?

**Comment by akhildevelops** [comment]
That project doesn't seem to be active. Will you accept my contribution if I develop a cli ?

**Comment by cksac** [comment]
sure, PR is welcome :)

**Comment by akhildevelops** [comment]
https://github.com/cksac/fake-rs/pull/209
