### ISSUE TITLE
de_de breaks the determinism tests 

### ISSUE THREAD

**Issue by xoryouyou** [cksac/fake-rs#211]
First of all sorry for the inconvenience.

The determinism tests fail, due to the newly introduced `ADDRESS_CITY_GEN_FN` which uses a separate `rand::thread_rng()`.
The test originally seeds the rng and provides fake with two identical instances here

[tests/determinism.rs#L10](https://github.com/cksac/fake-rs/blob/3dd26766b93ac4c258618b97c57d629aeb5f5adb/fake/tests/determinism.rs#L10)

I have no idea on top of my hat, but the footpring of `ADDRESS_CITY_GEN_FN`  needs to be changed from `Option<fn()->String>` to somehow include the original `thread_rng()`.

**Comment by cksac** [comment]
it is ok, I have introduced CityNameGenFn, https://github.com/cksac/fake-rs/blob/3dd26766b93ac4c258618b97c57d629aeb5f5adb/fake/src/faker/impls/address.rs#L35

the current test fail is fixed

**Comment by xoryouyou** [comment]
Ohh I have just pulled master and seen your changes.
Awesome then nevermind the issue, I'll close it.
