### ISSUE TITLE
Return original Chrono values instead of `String`s

### ISSUE THREAD

**Issue by seamlik** [cksac/fake-rs#22]
A project of mine stores `DateTime<Utc>` in some struct and would like to generate dummy timestamps for testing purposes. However this crate only returns `String`s, and I had to convert them back to `DateTime<Utc>`, which would be a bit slow and even unreliable.

**Comment by cksac** [comment]
@seamlik `DateTime<Utc>` implemented `Dummy`, so you can get a random value using something like `DateTime::dummy()`.
Although you can't have `after`, `before`, `between` like string version, as `Dummy` don't take argument to control how dummy values are generated.

For typed random value, I also created `dummy` crate, but `chrono` support is not yet implemented.

**Comment by seamlik** [comment]
Thank you for the advice, I just tried and it works.

It is indeed a bit limited as we can't get a typed value. Is this a feature or a bug?

**Comment by cksac** [comment]
@seamlik this crate initial designed to generate string like data only. Later introduced `Dummy` trait to generate typed value but it is bit limited. I would like to migrate to `Dummy` trait in `dummy` crate instead later.
