### ISSUE TITLE
proc macro panic

### ISSUE THREAD

**Issue by thedavidmeister** [cksac/fake-rs#29]
not sure if this is related to a rust version thing or if i did something wrong but i got this when trying to use `Dummy` derive

i'm using nightly `2019-07-14`

```
error: proc-macro derive panicked
  --> crates/holochain_persistence_api/src/hash.rs:12:5
   |
12 |     Dummy, PartialOrd, PartialEq, Eq, Ord, Clone, Debug, Serialize, Deserialize, DefaultJson, Default, Hash,
   |     ^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: Error { kind: UnsupportedShape("newtype"), locations: [], span: None }

```

**Comment by cksac** [comment]
@thedavidmeister the `Dummy` derive only support `struct` for now. `newtype`, i.e. `Custom(int)` is not supported. You need to manually implement it.
