### ISSUE TITLE
fake data generation seed

### ISSUE THREAD

**Issue by matteosister** [cksac/fake-rs#33]
is there a way to provide the generator with a seed, so that, given the same seed, I will always get the same fake data back?

I'm trying to mock an external web server, and I would like to return fake data based on a provided id.

Many thanks for the great lib!

**Comment by cksac** [comment]
you can use `fake_with_rng` instead
```rust
    // fixed seed rng
    let seed = [
        1, 0, 0, 0, 23, 0, 0, 0, 200, 1, 0, 0, 210, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0,
    ];
    let ref mut r = StdRng::from_seed(seed);
    for _ in 0..5 {
        let v: usize = Faker.fake_with_rng(r);
        println!("value from fixed seed {}", v);
    }
```

**Comment by matteosister** [comment]
thanks for the answer...but how can I use this approach to generate another kind of fake data, let's say a company name?

**Comment by matteosister** [comment]
ok I found the answer....sorry!

``` rust
CompanyName().fake_with_rng::<String, StdRng>(rng)
```
