### ISSUE TITLE
How does this work with uuids?

### ISSUE THREAD

**Issue by petar-dambovaliev** [cksac/fake-rs#42]
I am using this crate https://crates.io/crates/uuid 
From what i can see, there is no way to make it work with `fake`.
Is that correct?

**Comment by mothsART** [comment]
I'm not sure I understand.
An uuid is generated and unique.
How to distinguish a real uuid from a fake?

**Comment by petar-dambovaliev** [comment]
> I'm not sure I understand.
> An uuid is generated and unique.
> How to distinguish a real uuid from a fake?
You don't see the problem?
It doesn't work because the macro doesn't know what to do with this uuid type. And I can't implement it because both the type and trait are not defined by me.

**Comment by cksac** [comment]
Hi @petar-dambovaliev true if you want to use fake crate to generate uuid. What you can do is using Wrapper type and implement `Dummy` Or submmit PR to create faker for uuid crate similar to http, chrono crate.

But if the goal is getting an uuid, why use fake crate? As you can generated one from uuid crate directly

**Comment by petar-dambovaliev** [comment]
> Hi @petar-dambovaliev true if you want to use fake crate to generate uuid. What you can do is using Wrapper type and implement `Dummy` Or submmit PR to create faker for uuid crate similar to http, chrono crate.
> 
> But if the goal is getting an uuid, why use fake crate? As you can generated one from uuid crate directly

I have structs with many other fields, uuid is just one of them. I want to generate random data for those structs. Therefore, I can't use uuid to generate it, if I want to use the dummy macro.

**Comment by cksac** [comment]
Hi @petar-dambovaliev , I see. You can achieve by below your local struct as faker for Uuid.
```rust
use fake::{Dummy, Fake, Faker};
use rand::Rng;
use uuid::Uuid;

#[derive(Debug, Dummy)]
pub struct Foo {
    #[dummy(faker = "UuidFaker")]
    id: Uuid,
}

pub struct UuidFaker;

impl Dummy<UuidFaker> for Uuid {
    fn dummy_with_rng<R: Rng + ?Sized>(_: &UuidFaker, rng: &mut R) -> Self {
        Uuid::from_u128(Faker.fake_with_rng(rng))
    }
}

fn main() {
    let foo: Foo = Faker.fake();
    println!("{:?}", foo);
}
```

**Comment by petar-dambovaliev** [comment]
Cool, thanks.

**Comment by SpyMachine** [comment]
Is this documented anywhere? I feel like it should be if it isn't. I couldn't find it.
