### ISSUE TITLE
Readme example incomplete

### ISSUE THREAD

**Issue by mooreniemi** [cksac/fake-rs#44]
Hi! Happy to see this library in Rust. :) But trying to follow the example it doesn't work as documented.

### rustup show

```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/alex/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16)
```

### what I ran

Cargo.toml contains the `derive` feature, for `Dummy`.

```
use fake::{Dummy, Fake, Faker};

#[derive(Debug, Dummy)]
pub struct Foo {
    #[dummy(faker = "1000..2000")]
    order_id: usize,
    customer: String,
    paid: bool,
}

fn main() {
    // type derived Dummy
    let f: Foo = Faker.fake();
    println!("{:?}", f);
}
```

I expected it to print `Foo`.

#### no rand

```
error[E0433]: failed to resolve: use of undeclared crate or module `rand`
 --> src/main.rs:3:17
  |
3 | #[derive(Debug, Dummy)]
  |                 ^^^^^ use of undeclared crate or module `rand`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

#### fixed once I add `rand`

Oke doke. I add `use rand;` and then in the Cargo.toml, I add `rand = "0.7.3"` (I see that in Cargo.lock as your version).

### suggestion

Add Readme block describing the required dependency on `rand` or add it as a `features` entry?

**Comment by cksac** [comment]
thanks, updated readme

**Comment by francisdb** [comment]
For people arriving here in 2024: see https://github.com/cksac/fake-rs/pull/197
