### ISSUE TITLE
Extend fake-rs to cover more of Faker's functionality

### ISSUE THREAD

**Issue by llogiq** [cksac/fake-rs#62]
Hi there! We are currently using faker (via pyo3) in [synth](https://github.com/getsynth/synth) and want to move to use fake-rs. However, to do that, we'd want fake-rs to match more of the functionality faker provides.

So we'd like to give this project a boost by trying to speed up that implementation work on that (I did the creditcardnumber stuff to check how hard that is). But before we go that route (and risk overwhelming you with PRs) I wanted to openly address you to learn your needs as a maintainer of this project and how we can best work together to our mutual benefit.

**Comment by cksac** [comment]
Hi, I do intend to include new maintainers to this project. If you like, I can added you as maintainer :)

**Comment by llogiq** [comment]
Sure thing, I'll be glad to help.

**Comment by cksac** [comment]
Hi @llogiq , I have invited you as collaborator.
