### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by evgeniy-r** [cksac/fake-rs#65]
Hello!

Could you make a new release, please?

We need this [fix](https://github.com/cksac/fake-rs/commit/aee37e1f4a03551f55fa525eed2f2e1782d27c7a) for our [tool](https://github.com/datanymizer/datanymizer).

**Comment by cksac** [comment]
hi, fake = "2.4.1" released

**Comment by evgeniy-r** [comment]
Thank you
