### ISSUE TITLE
Custom derive #[derive(Dummy)]

### ISSUE THREAD

**Issue by cksac** [cksac/fake-rs#7]
implement procedural macro for #[derive(Dummy)]

**Comment by mekagoza** [comment]
I'd like to work on this. First, a question: writing a procedural macro requires it to be in a different crate [1].

So should I just create a new repo and notify you about it, or do I need to make this repo into a Cargo workspace project with two crates?


1. https://doc.rust-lang.org/beta/book/first-edition/procedural-macros.html

**Comment by cksac** [comment]
Hi Mekagoza,

Thanks for interest in helping out.
I would prefer to turn the repo into workspace project. And I am also thinking separate dummy into it’s own crate. What do you think?

Best regards
ks

從我的 iPhone 傳送

**Comment by cksac** [comment]
sounds good to me, thx

**Comment by cksac** [comment]
close, will refactor to use [https://crates.io/crates/dummy](dummy) crate later.

**Comment by cazgp** [comment]
Hey! What's the status of this? Am thinking of doing something similar, but don't want to repeat work...

**Comment by cksac** [comment]
@cazgp, yes we better to work together to reduce repeat work.
The `dummy` crate has been done, and `Dummy` trait in this crate will be deprecated later.
For the custom derive implementation for `Dummy` in `dummy` crate, It is not start yet.
Not sure any work from @mekagoza can be reuse.

**Comment by cazgp** [comment]
https://gitlab.com/cazgp/fake-derive

**Comment by cksac** [comment]
@cazgp looks you generate an `Fake` trait in your custom derive, will you consider to generate implementation of [`Dummy<Any>`](https://github.com/cksac/dummy-rs/blob/master/src/lib.rs) defined in `dummy` crate?
