### ISSUE TITLE
Create a user agent faker

### ISSUE THREAD

**Issue by svenstaro** [cksac/fake-rs#9]
You could use a list to do this such as [this](https://github.com/tamimibrahim17/List-of-user-agents) or [this](https://github.com/andresriancho/w3af/blob/master/w3af/core/data/user_agent/user-agent-list.txt).

**Comment by cksac** [comment]
#10 do you think it is enough to just sample some of the user agent in the faker?

**Comment by svenstaro** [comment]
I think it would be nice to have a fairly complete list. I'm attaching a deduplicated list that I think should be included but of course you are free to remove some entries from that.

**Comment by cksac** [comment]
Thanks for consolidate the list. I have sample some of them into the faker in order not to increase the crate size a lot.
