### ISSUE TITLE
help on uuid v1 compat ...

### ISSUE THREAD

**Issue by jrouaix** [cksac/fake-rs#90]
Hello,

I'm struggling hard after the update of an other lib to using `uuid v1^`. 
Since then this lib (async-graphql) and fake do not play together anymore.

Do you see a way I can force fake to use uuid v1 without forking it ?

**Comment by cksac** [comment]
released 2.5.0, please try

**Comment by jrouaix** [comment]
🎉  working just fine !
Thank you @cksac ! very much !
