### ISSUE TITLE
Is it possible to generate fake data from a template?

### ISSUE THREAD

**Issue by ntrp** [cksac/fake-rs#97]
I cannot find it in the docu/code and I have no clue how could I make it work myself in rust. I am referring to this feature from the faker.js lib https://fakerjs.dev/api/fake.html.

I need this feature because I want to define my object in a JSON (more likely RSON) and I need to define dynamically the fake template. Similar to the dummy derive but the templates are loaded from an external source at runtime.

**Comment by cksac** [comment]
it seems required to parse the template string or something similar. not in the scope of the crate
